function [tracks] = iniTrack(centerLocation)
tracks = struct(...
    'id', {}, ...  % 轨迹ID
    'x',{},... % 轨迹x坐标
    'y',{},... % 轨迹y坐标
    'vx',{},...
    'vy',{},...
    'ax',{},...
    'ay',{},...
    'death',{},...
    'P',{}, ...
    'lx',{},...
    'ly',{},...
    'w',{}, ...
    'h',{});

[Height,~]=size(centerLocation);
Q=[1,0,0,0,0,0;...
    0,1,0,0,0,0;...
    0,0,1,0,0,0;...
    0,0,0,1,0,0;...
    0,0,0,0,1,0;...
    0,0,0,0,0,1;];

for i=1:Height
    tracks(i).id=i;
    tracks(i).x=centerLocation(i,1);
    tracks(i).y=centerLocation(i,2);
    tracks(i).vx=0;
    tracks(i).vy=0;
    tracks(i).ax=0;
    tracks(i).ay=0;
    tracks(i).death=0;
    tracks(i).P=Q;
    tracks(i).lx=0;
    tracks(i).ly=0;
    tracks(i).w=0;
    tracks(i).h=0;
end


end

